Add RV32X hwloop covergroups
XavierAubert/core-v-verif pull request #63
Opened 2023-10-04 07:57 UTC by dd-baoshan

I have competed the initial version for hwloop coverage which should covers items 59, 60, 61, 62, 63 
-	I implemented covergroup for  62 and 63 might be different than the intention of “read or  toggle”, @Xavier, you might need to review on this part as you defined item 62 and 63. (In my opinion, toggle is too much).
-	Please review these these new covergroups to see if there is any missing bins or improvements needed.
-	Please try to run with any hwloop test (short simtime test preferable) to see any issue I might overlook. Currently I only run tested with single test.

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/1de119f2-49d5-4e81-815b-27ab73398cb6)

-	Example new covergroups for hwloop (total 3 of them)

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/65b91bcf-b2d5-4b4c-bfe4-47df8cd6f305)

-	Example csr covergroup

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/533371cc-fe71-433d-b662-0dad5bc5f9df)

-	Example cg for hwloop features

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/5b140f43-098f-4ff5-a361-bed4edb1a44a)

2023-10-04 09:19 UTC, dd-vaibhavjain commented
@XavierAubert Please wait to resolve review before merging

2023-10-04 09:25 UTC, dd-vaibhavjain requested changes

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  virtual rvviTrace #( .NHART(NHART), .RETIRE(RETIRE)) rvvi_vif;
Need to use RVFI, since RVVI comes from Imperas.

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/uvme_cv32e40p_pkg.flist
> +${IMPERAS_HOME}/ImpPublic/source/host/rvvi/rvviTrace.sv
This solution is not generic if we are using Imperas. Thats why rvvi cant be used.

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
iff condition seems like wont be met everytime. Since it uses "&&" becuase not sure If everytime all 3 will be triggered on same cycle, especially when not using cv.setup/i

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    // todo: is crossing lpcount==0 is necessary to make sure hwloop body instruction will not executed? (not a normal usecase)
lpcount==0 will still execute hwloop body

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpend_zero           = {32'h0};
setting end address 0 ? Currently dont have a test for this, also would mean start address will be 0xFFFF_FFxx ? Not sure about this being valid.

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
Currently no test. Need to think if this is required.

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpcount_range_low      = {[32'h0000_FFFF : 32'h0000_0001]};
Currently tests only cover this range. Higher loop count is going to be very long running tests. So have to see if really useful.

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
Not sure if I understand fully, but will this field be qualified for each instruction, or only at entry and exit of hwloop ?

2023-10-04 09:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
Does this means sampling happens at the end of the loop_count =0 ?

2023-10-05 00:57 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
for long setup, the condition is check with logic below. 
![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/5c2562cd-13f1-4e8e-bae4-98c4bbdb1717)

2023-10-05 00:59 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    // todo: is crossing lpcount==0 is necessary to make sure hwloop body instruction will not executed? (not a normal usecase)
this is what I thought as well. it is just execute like normal instructions. this mean lpcount==1 and lpcount==0 will behave the same if I understand correctly

2023-10-05 01:03 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpend_zero           = {32'h0};
ya, this cross cover points seems to have some invalid scenarios. I will think about this part again.

2023-10-05 01:07 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
To me this is not a valid scenario to have lpstart==0. 
I put this because in assignment of rvfi to rvvi, when signals changed from x to default_0, it trigger the wb to high. (actually, seems to me is rvfi to rvvi issue). I put this to prevent this goes into illegal bins. Anyway, I think I will remove this impossible bin.

2023-10-05 01:09 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpcount_range_low      = {[32'h0000_FFFF : 32'h0000_0001]};
noted, if this case, i can just comment out those bins not covered range. Anytime in future need to enable can just uncommented out the bins.

2023-10-05 01:15 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
the logic basically captures every instruction in the loops when hwloop execute at first time of its looop execution.
after the first loop (a.k.a subsequent loops), it will not sample again the same instructions (by assuming that all the captured instructions should be same for every loop; I was thinking it is nice to have a check that ensure all instructions maintain the same list and in order for every subsequent loop)

2023-10-05 01:15 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
yes

2023-10-05 01:27 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  virtual rvviTrace #( .NHART(NHART), .RETIRE(RETIRE)) rvvi_vif;
Initially I was hesitated to use rvvi as I had the same thought as you. But below reasons driving me to use rvvi eventually. 

1) In cv32e40p v2 verif environment, we are using Imperas to capture the functional coverage for all the supported standards including the RV32X (custm instructions). without Imperas, we do not have complete coverage information.
2) hwloop coverage here to complement the lacking part of Imperas coverage on RV32X. In v2 verif env, if want to analyze coverage, we need to include Imperas else it seems meaningless.
3) Using rvfi will make it generic but we also need to have other functional coverage that covered by Imperas (such as RV32F, RV32X, etc...) this might be implemented in future version of verif env. at this time, maybe the next users can start to implement them.

I am fine to convert to rvfi but I would like to hear your opinions regarding above.

2023-10-05 02:05 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  virtual rvviTrace #( .NHART(NHART), .RETIRE(RETIRE)) rvvi_vif;
How I see this is, Imperas functional coverage is useful but it is not criteria for closure, but all isacov and specific functional coverage models defined inside core-v-verif would be required to achieve full 100% coverage.
It is more otherway round, that Imperas cover model is add-on. Ideally we want to all the functional coverage as per the verif plan in core-v-verif, and hence it should not be dependent on any external module (especially like Imperas which is licensed).
And anyway we need to reconnect rvfi for other isacov, so I see no reason not to use RVFI here as well.

We can use RVVI if that RVVI interface is local to core-v-verif and we want to create it. But at the moment I am not sure we have bandwidth for that.

2023-10-05 02:17 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
It may need to revisit, I am not sure it will work correctly in all cases. Especially with interrupts and debug.
1 case is before writing all 3, we got an interrupt and inside interrupt handler new values got written on these CSRs, that may disrupt this struct.

2023-10-05 02:20 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
Theoretically it is possible to achieve this scenario. Is it at the time of reset release, all wb are set to 1?

2023-10-05 02:24 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpend_zero           = {32'h0};
I was thinking maybe theoretically it is also possible, but it is like trying to do things which may not be ever triggered. But a hwloop towards end of mem space may be possible to create such a scenario.  
But again from functional coverage it only makes sense if we even want to test this, which I dont think we do at the moment.
Overall hwloop really needs to be handled well in toolchain else there can be plenty of issues.

2023-10-05 02:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    // todo: is crossing lpcount==0 is necessary to make sure hwloop body instruction will not executed? (not a normal usecase)
Yes thats true.

2023-10-05 02:29 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  virtual rvviTrace #( .NHART(NHART), .RETIRE(RETIRE)) rvvi_vif;
I plan to create a simple interface just to capture relevant information from rvfi that needed for hwloop cov and pass it into configdb. this will prevent using Imperas interface and local to verif env. what do you think?

2023-10-05 02:31 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
The check for subsequent instructions in loop is not required in coverage model. The reference model will catch any issue in program flow.  
I think 1 time capturing of hwloop instructions is sufficient from coverage perspective.

Also if execute_instr_in_hwloop[i] is not checked everytime, the case which may disrupt is interrupts, exceptions and debug request inside hwloops that will shift the program execution out of hwloop and then those instructions will be wrongly captured as part of hwloop.

2023-10-05 02:35 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  virtual rvviTrace #( .NHART(NHART), .RETIRE(RETIRE)) rvvi_vif;
Yes its the right approach I think. We need to but make it RVVI-like  and also consider the fact that it needs to work for ISACOV and hence be compatible with what ISACOV in core-v-verif needs.

2023-10-05 02:39 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
in this case, I need to get some of the signals to indicate such scenarios (interrupts, exceptions and debug request) occur. once occur, it paused and instructions sampling stops. it will resume back once exit these scenarios. We can discuss more on this later once I made changes based on other feedbacks.

2023-10-05 02:40 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
Ok. I would like to highlight that if this is done, there are long random tests in hwloop running potentially 200*100*100 = 2 Million instructions. And depending on what is data structure size per instruction in SV for this queue item, you would need 2M * stuct_size of memory and potentially have a performance impact.

I am not sure if sampling all instructions inside HWLOOP is worth it now.  
But if we keep this, maximum 1 loop sample shd be sufficient.

2023-10-05 02:43 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
the sampling happen when count=0 but the instruction list sample for 1 loop (for both inner and outer) only in my implementation.

2023-10-05 02:45 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
It is not so straight forward. Only reliable check is to check PC value w.r.t to lpstart{0/1} and lpend{0/1} everytime. And keep this check disabled if lpcount=0 (to avoid impacting non-hwloop tests)

2023-10-05 02:48 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          hwloop_stat.execute_instr_in_hwloop[i] = 1'b1;
understand, let me think about this and we can review the logic again and use a simple testcase of such scenarios to try out

2023-10-05 02:51 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
If the list only adds instructions for 1 loop iteration, then it is fine. Though if possible to remove count==0 sampling may be better.  I think those tests programming count==0 in hwloop may not be best to use for functional coverage.

2023-10-05 02:53 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
as long as rvfi is capturing these writes, it should work. 
there is one limitation here for long setup coverage capture (what I can think of now based on current logic implementation) which is ->  user need to configure all three (start, end, count) every time during long setup then then only it will sample

2023-10-05 02:55 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    ) begin : SAMPLE
sure. Will amend to remove count==0

2023-10-05 02:59 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
Consider this:
CSRW lpstart0
CSRW lpend0
-> interrupt
(jump to interrupt handler)
-> New HWLOOP used in Interrupt handler

CSRW lpstart0 ) **(will the csr_update_cnt == 3 be true now ? )** 
CSRW lpend0
CSRW lpcount0

..
mret

(back to original HWLOOP)
CSRW lpcount0

2023-10-05 03:08 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
I need clarifiation for below scenarios
>>>

CSRW lpstart0 <value A1>
CSRW lpend0	  <value A2>
-> interrupt
(jump to interrupt handler)
-> New HWLOOP used in Interrupt handler

CSRW lpstart0 <value B1> ) (will the csr_update_cnt == 3 be true now ? ) bsm: yes, this will break the logic (need updae to accomodate such scenario)
CSRW lpend0   <value B2>
CSRW lpcount0 <value B3>

..
mret

(back to original HWLOOP)
bsm: do we need to reconfigure <value A1 and value A2>> after exit because they were overriden during entering the interrupt?
CSRW lpcount0 <value A3>

>>>>

2023-10-05 03:17 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
No not inside the main code, A1 and A2 CSR write instructions cant be executed again as the PC would be set to next instruction (A3) after return from handler.
But these CSRs write will happen in interrupt routine during "restore" stage of save-restore like this:  
Ideally if any handler needs to use HWLOOP it must save the existing state of HWLOOP CSR on stack and restore these CSR back to original value before exiting the handler routine.  
So this restore of CSRs will actually write all hwloop 0/1 CSRs. (again may be a case you would need to handle in this situation)  
And thus program flow is maintained again.

2023-10-05 03:17 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
Yes, based on below implementation in dv_wrapper, changes in addr will lead to wb=1; during out of reset, all hwloop csr changed from X to 1, thus all wb set to 1.

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/3a849785-4457-4f6a-be8d-4676d57602f5)

2023-10-05 03:21 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
Then count != 0 maybe required also to make sure the sampling is for correct usecase.

2023-10-05 03:21 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
I think should be fine in this case then, restore means the registers will changed back to A1 and A2 and this will elad to wb set to 1 (base on dv_wrapper). 
The only issue here is below --> CSRW lpstart0 "value B1" ) (will the csr_update_cnt == 3 be true now ? ) bsm: yes, this will break the logic (need updae to accomodate such scenario)

2023-10-05 03:24 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
> Then count != 0 maybe required also to make sure the sampling is for correct usecase.

can you explain more on above. not quite get what you mean.

2023-10-05 03:27 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    cp_lpstart_0 : coverpoint (csr_hwloop.lp_start[0]) iff (csr_hwloop.lp_start_wb[0] && csr_hwloop.lp_end_wb[0] && csr_hwloop.lp_count_wb[0]) {
restore will also cause this csr_udpate_cnt == 3 before exiting.

2023-10-05 03:29 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      bins lpstart_zero         = {32'h0};
I mean to avoid sampling any CSR writes for HWLOOP, only valid CSR writes to sample should be when count != 0 along with wb==1 for all 3 CSRs

2023-10-18 06:58 UTC, dd-baoshan commented
updated redirected to new PR #67

2023-10-18 06:58 UTC, closed without merging