Add RV32X hwloop covergroups with updates based on feedback
XavierAubert/core-v-verif pull request #67
Opened 2023-10-18 06:57 UTC by dd-baoshan

Updates based on previous PR #63

2023-10-19 03:01 UTC, dd-vaibhavjain commented
First basic question is what happened to the older PR which was opened for this. 
Basically now we lose the connection and we are not aware if those points which were raised earlier are addressed in this PR.
At the very minimum, some comments or references would have been helpful.

2023-10-19 03:25 UTC, dd-vaibhavjain requested changes

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          `CHECK_N_SAMPLE_CSR_HWLOOP(sub);
what is "sub" ?
And what coverage are we expecting here.

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          if (is_ebreak || is_ecall || is_illegal) enter_hwloop_sub = 1;
what about debug request?

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  parameter int NHART   = 1,
why we need these params ?

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins other_range    = default; \
illegal here is not correct, other values are allowed also

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins  others_grp  = default; // higher range is not covered now due to limited generated codespace (amend if needed) \
Illegal not correct

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins  others_grp  = default; // higher range is not covered now due to limited generated codespace (amend if needed) \
illegal not correct

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_tb_ifs.sv
> +    assign csr[``CSR_ADDR]    = csr_``CSR_NAME``_w | csr_``CSR_NAME``_r; \
I dont fully understand what is happening here. Can you explain?

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      if (hwloop_stat_``TYPE``.hwloop_csr.lp_count[i] != 0) begin \
Does it mean we are still sampling for all Loop iterations?

2023-10-19 03:25 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      wildcard bins instr_lui = {INSTR_LUI}; \
last time I tried to add all the defines in common package. Because using tracer was not ideal here. And there is no guarantee that will be maintained in future.

2023-10-19 03:26 UTC, dd-vaibhavjain commented
I think there are many things again in this PR for discussion, if you prefer to call review discussion call, that also works.

2023-10-19 04:47 UTC, dd-baoshan commented
> I think there are many things again in this PR for discussion, if you prefer to call review discussion call, that also works.

Sure, We can have one in Next Monday. I will include you and Xavier.

2023-10-19 04:48 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      if (hwloop_stat_``TYPE``.hwloop_csr.lp_count[i] != 0) begin \
Nope, it is still sampling one loop only for hwloop iterations

2023-10-19 05:14 UTC, dd-baoshan commented
> First basic question is what happened to the older PR which was opened for this. Basically now we lose the connection and we are not aware if those points which were raised earlier are addressed in this PR. At the very minimum, some comments or references would have been helpful.

Sorry that I open the new PR on this because I thought the previous PR has too many comments. I did major updates which it might be difficult to review if using the same PR and also it will lead to longer comments. I tought a clean PR will be easy to review.

Let me know if you want to review it in older PR, I can reopen that PR and merged  and push the changes on to it.

2023-10-19 05:15 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +  parameter int NHART   = 1,
Yes, this class no longer a prametrrized class. I will remove them.

2023-10-19 05:18 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          `CHECK_N_SAMPLE_CSR_HWLOOP(sub);
sub is to collect the secondary hwloops that exercise in handle such as the scenario that stated below. teh coverage collection is the same as what have defined in covergroups

![image](https://github.com/XavierAubert/core-v-verif/assets/131629054/88cfa641-ebb9-4206-b719-9c7bf152173d)

2023-10-19 05:21 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins other_range    = default; \
Yes, ti can support upto 32bits but in the tests, we never exercise such ranges. Should i uncommented out lines 104 and 105?

2023-10-19 05:32 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins  others_grp  = default; // higher range is not covered now due to limited generated codespace (amend if needed) \
should we cover full range 32bits ? or  made it generic and in case the tests does not exercise high range, we can exclude them. what do you think? 
if define full range (start, end, count), then illegal bins no longer apply.

2023-10-19 05:33 UTC, dd-baoshan commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_tb_ifs.sv
> +    assign csr[``CSR_ADDR]    = csr_``CSR_NAME``_w | csr_``CSR_NAME``_r; \
Let have this in review discussion.

2023-10-19 05:35 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          if (is_ebreak || is_ecall || is_illegal) enter_hwloop_sub = 1;
This is the missing part. I need to gather some inputs from you regarding hwloop in debug usecase and an example test.

2023-10-19 05:37 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins other_range    = default; \
Excercise or not is not the question here.
Any cover bin is illegal if we want to raise a fatal error in simulation, i.e., we dont expect such value to be generated/sampled ever.

But if we dont want to record or cover some legal value it should be ignored not illegal.

2023-10-19 05:39 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins other_range    = default; \
thanks..I missed out that we have  ignore_bins

2023-10-19 05:51 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      wildcard bins instr_lui = {INSTR_LUI}; \
May I know where is the file located?
I checked with Yoann and he said the tracer pkg need to be maintained because it is used in RVFI and RVFI is a must exist component compared to tracer.

2023-10-19 05:52 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins  others_grp  = default; // higher range is not covered now due to limited generated codespace (amend if needed) \
will update to ignore_bins

2023-10-19 05:52 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      illegal_bins  others_grp  = default; // higher range is not covered now due to limited generated codespace (amend if needed) \
will update to ignore_bins

2023-10-20 02:15 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +          `CHECK_N_SAMPLE_CSR_HWLOOP(sub);
This one is not required. 
I was explaining the case where the previous logic would break. But that does not mean we need a coverage like this. 
It can be covered by a particular test, without having to create a complex functional coverage for this. Not much benefit here.

2023-10-20 02:19 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +      if (hwloop_stat_``TYPE``.hwloop_csr.lp_count[i] != 0) begin \
Yes maybe would need some clarification how does that work, from here it looks like it will sample for all iterations as long as count != 0

2023-10-25 08:32 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    bit [(XLEN-1):0] lp_start     [HWLOOP_NB];
lp_start/end/count have no spec reference for XLEN parameter. So it should not be XLEN

2023-10-25 08:43 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_rv32x_hwloop_covg.sv
> +    bit [(XLEN-1):0] lp_start     [HWLOOP_NB];
noted.

2023-11-06 08:11 UTC, dd-baoshan commented
all the updates based on feedback is available in  #81 . Once merged, this ticket can be closed

2023-11-06 09:14 UTC, dd-baoshan commented
closed as #81 is merged. All the files update should be referred to #81

2023-11-06 09:14 UTC, closed without merging